<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<ApplicationIcon>Resources\Images\Logo\ElementalSpirit.ico</ApplicationIcon>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<Compile Update="Presentation\Forms\BossDialogueForm.cs">
			<SubType>Form</SubType>
		</Compile>
		<Compile Update="Presentation\Forms\BossDialogueForm.Designer.cs">
			<DependentUpon>BossDialogueForm.cs</DependentUpon>
		</Compile>
		<Compile Update="Presentation\Forms\GameForm.cs">
			<SubType>Form</SubType>
		</Compile>
		<Compile Update="Presentation\Forms\GameForm.Designer.cs">
			<DependentUpon>GameForm.cs</DependentUpon>
		</Compile>
		<Compile Update="Presentation\Forms\GuideAndTeamForm.cs">
			<SubType>Form</SubType>
		</Compile>
		<Compile Update="Presentation\Forms\GuideAndTeamForm.Designer.cs">
			<DependentUpon>GuideAndTeamForm.cs</DependentUpon>
		</Compile>
		<Compile Update="Presentation\Forms\IntroForm.cs">
			<SubType>Form</SubType>
		</Compile>
		<Compile Update="Presentation\Forms\IntroForm.Designer.cs">
			<DependentUpon>IntroForm.cs</DependentUpon>
		</Compile>
		<Compile Update="Presentation\Forms\LeaderboardForm.cs">
			<SubType>Form</SubType>
		</Compile>
		<Compile Update="Presentation\Forms\LeaderboardForm.Designer.cs">
			<DependentUpon>LeaderboardForm.cs</DependentUpon>
		</Compile>
		<Compile Update="Presentation\Forms\MainMenuForm.cs">
			<SubType>Form</SubType>
		</Compile>
		<Compile Update="Presentation\Forms\MainMenuForm.Designer.cs">
			<DependentUpon>MainMenuForm.cs</DependentUpon>
		</Compile>
		<Compile Update="Presentation\Forms\PlayerNameDialog.cs">
			<SubType>Form</SubType>
		</Compile>
		<Compile Update="Presentation\Forms\PlayerNameDialog.Designer.cs">
			<DependentUpon>PlayerNameDialog.cs</DependentUpon>
		</Compile>
		<Compile Update="Presentation\Forms\Settings\SettingsForm.cs">
			<SubType>Form</SubType>
		</Compile>
		<Compile Update="Presentation\Forms\Settings\SettingsForm.Designer.cs">
			<DependentUpon>SettingsForm.cs</DependentUpon>
		</Compile>
		<Compile Update="Presentation\Dialogs\BaseDialog.cs">
			<SubType>Form</SubType>
		</Compile>
		<Compile Update="Presentation\Dialogs\BaseDialog.Designer.cs">
			<DependentUpon>BaseDialog.cs</DependentUpon>
		</Compile>
		<Compile Update="Presentation\Dialogs\ConfirmationDialog.cs">
			<SubType>Form</SubType>
		</Compile>
		<Compile Update="Presentation\Dialogs\ConfirmationDialog.Designer.cs">
			<DependentUpon>ConfirmationDialog.cs</DependentUpon>
		</Compile>
		<Compile Update="Presentation\Dialogs\InformationDialog.cs">
			<SubType>Form</SubType>
		</Compile>
		<Compile Update="Presentation\Dialogs\InformationDialog.Designer.cs">
			<DependentUpon>InformationDialog.cs</DependentUpon>
		</Compile>
		<EmbeddedResource Update="Presentation\Forms\MainMenuForm.resx">
			<DependentUpon>MainMenuForm.cs</DependentUpon>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<Content Include="Resources\Images\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Lang\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="NAudio" Version="3.1.0" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="Resources\Audio\Music\forest_theme.mp3">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\Audio\Music\boss_theme.wav">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\Audio\Music\intro_theme.mp3">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\Audio\Music\menu_theme.mp3">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\Audio\Music\menu_theme.wav">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\Audio\SFX\enemy_die.mp3">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\Audio\SFX\enemy_hurt.mp3">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\Audio\SFX\jump.mp3">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\Audio\SFX\lose.mp3">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\Audio\SFX\hurt.mp3">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\Audio\SFX\shot.mp3">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\Audio\SFX\slash.mp3">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\Audio\SFX\waterfall.mp3">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\Audio\SFX\win.mp3">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\Audio\SFX\coin.flac">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>